version: "3.8"

services:
  server:
    restart: always
    image: dockersamples/visualizer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1010:8080

  mongo:
    image: portainer/portainer:1.24.2-alpine
    restart: always
    ports:
      - 1020:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock